release:
  development_branch: develop
  release_branch: master
changelog:
  path: CHANGELOG.md
  item_template: |
    {{range .Sections}}### {{.EndTaggedCommit.Tag}} ({{.EndTaggedCommit.Date.Format "2006 Jan 02"}})
    
    {{range $idx, $commit := .Commits}}* {{$commit.Message}}{{ "\n" }}{{end}}
    {{end}}